{
 "title": "Clientes",
 "description": "Dashboard voltado ao acompanhamento de métricas relacionadas aos clientes de todas as filiais.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Quantidade de Clientes",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(\"clienteId\") FROM \"Cliente\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Distribuição de Clientes por Gênero",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT genero, COUNT(genero) FROM \"Cliente\" GROUP BY genero"
    }
   ]
  },
  {
   "title": "Maiores Compradores",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT nome AS \"Nome\", cidade AS \"Cidade\", idade AS \"Idade\", \"canalCompra\" as \"Meio\", \"totalCompra\" AS \"Valor Total (R$)\" FROM \"Cliente\" LIMIT 50"
    }
   ]
  },
  {
   "title": "Vendas por Meio",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(\"canalCompra\"), \"canalCompra\" FROM \"Cliente\" GROUP BY \"canalCompra\""
    }
   ]
  },
  {
   "title": "Distribuição de Clientes por Idade",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT idade FROM \"Cliente\""
    }
   ]
  },
  {
   "title": "Compras por Meio - Até 24 Anos",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT \"canalCompra\" AS \"Meio\", COUNT(\"canalCompra\") FROM \"Cliente\" WHERE idade <= 24 GROUP BY \"canalCompra\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Compras por Meio - De 25 a 35 Anos",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT \"canalCompra\" AS \"Meio\", COUNT(\"canalCompra\") FROM \"Cliente\" WHERE (idade <= 35 AND idade > 24) GROUP BY \"canalCompra\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Compras por Meio - De 36 a 50 Anos",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT \"canalCompra\" AS \"Meio\", COUNT(\"canalCompra\") FROM \"Cliente\" WHERE (idade <= 50 AND idade > 35) GROUP BY \"canalCompra\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Compras por Meio - Acima de 50 Anos",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT \"canalCompra\" AS \"Meio\", COUNT(\"canalCompra\") FROM \"Cliente\" WHERE idade > 50 GROUP BY \"canalCompra\" LIMIT 50 "
    }
   ]
  }
 ]
}