{
 "title": "Colaboradores",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Quantidade de Colaboradores por Filial",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \"Loja\".\"nome\" AS \"Nome da Loja\", COUNT(\"Colaborador\".\"colaboradorId\") AS \"Total de Colaboradores\" FROM \"Colaborador\" INNER JOIN \"Loja\" ON \"Colaborador\".\"lojaId\" = \"Loja\".\"lojaId\" GROUP BY \"Loja\".\"nome\""
    }
   ]
  },
  {
   "title": "Quantidade de Colaboradores por Função",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"funcao\" AS \"Função\", COUNT(\"colaboradorId\") AS \"Quantidade\" FROM \"Colaborador\" GROUP BY \"funcao\""
    }
   ]
  },
  {
   "title": "Avaliação Média dos Colaboradores por Filial",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \"Loja\".\"nome\" AS \"Nome da Loja\", AVG(\"Colaborador\".\"avaliacaoDesempenho\") AS \"Nota Média\" FROM \"Colaborador\" INNER JOIN \"Loja\" ON \"Colaborador\".\"lojaId\" = \"Loja\".\"lojaId\" GROUP BY \"Loja\".\"nome\""
    }
   ]
  },
  {
   "title": "Média de Horas Semanais Trabalhadas por Filial",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \"Loja\".\"nome\" AS \"Nome da Loja\", AVG(\"horasSemanais\") AS \"Média de Horas Trabalhadas\" FROM \"Colaborador\" INNER JOIN \"Loja\" ON \"Colaborador\".\"lojaId\" = \"Loja\".\"lojaId\" GROUP BY \"Loja\".\"nome\""
    }
   ]
  },
  {
   "title": "Colaboradores com Maior Avaliação de Desempenho",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT \"Colaborador\".\"nome\" AS \"Nome\", \"Loja\".\"nome\" AS \"Nome da Loja\", \"Colaborador\".\"horasSemanais\" AS \"Horas Semanais Trabalhadas\", \"Colaborador\".\"avaliacaoDesempenho\" FROM \"Colaborador\" INNER JOIN \"Loja\" ON \"Colaborador\".\"lojaId\" = \"Loja\".\"lojaId\" ORDER BY \"Colaborador\".\"avaliacaoDesempenho\" DESC"
    }
   ]
  },
  {
   "title": "Colaboradores com Menor Avaliação de Desempenho",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT \"Colaborador\".\"nome\" AS \"Nome\", \"Loja\".\"nome\" AS \"Nome da Loja\", \"Colaborador\".\"horasSemanais\" AS \"Horas Semanais Trabalhadas\", \"Colaborador\".\"avaliacaoDesempenho\" FROM \"Colaborador\" INNER JOIN \"Loja\" ON \"Colaborador\".\"lojaId\" = \"Loja\".\"lojaId\" ORDER BY \"Colaborador\".\"avaliacaoDesempenho\" ASC"
    }
   ]
  },
  {
   "title": "Quantidade de Vendas Realizadas por Filial",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT \"Loja\".\"nome\" AS \"Nome da Loja\", SUM(\"vendasRealizadas\") AS \"Quantidade de Vendas Realizadas\" FROM \"Colaborador\" INNER JOIN \"Loja\" ON \"Colaborador\".\"lojaId\" = \"Loja\".\"lojaId\" GROUP BY \"Loja\".\"nome\""
    }
   ]
  },
  {
   "title": "Quantidade de Vendas Realizadas por Colaborador",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT \"Colaborador\".\"nome\" AS \"Nome\", \"Loja\".\"nome\" AS \"Nome da Loja\", \"Colaborador\".\"vendasRealizadas\"  FROM \"Colaborador\" INNER JOIN \"Loja\" ON \"Colaborador\".\"lojaId\" = \"Loja\".\"lojaId\" ORDER BY \"Colaborador\".\"vendasRealizadas\" DESC"
    }
   ]
  }
 ]
}