{
 "title": "Custos Operacionais",
 "time": { "from": "2013-12-11T00:00:00.000Z", "to": "2024-12-13T00:00:00.000Z" },
 "panels": [
  {
   "title": "Custos Operacionais Totais por Mês",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(\"valorMensal\"), $__timeGroupAlias(\"data\",30d) FROM \"CustoOperacional\" GROUP BY \"data\" ORDER BY \"data\" ASC"
    }
   ]
  },
  {
   "title": "Custos Operacionais ao Longo do Tempo em Reais - Filial Loja Borges S.A.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(\"valorMensal\") AS \"Custo Mensal\", $__timeGroupAlias(\"data\",30d) FROM \"CustoOperacional\" WHERE \"lojaId\" = 1 GROUP BY \"data\" ORDER BY \"data\" ASC"
    }
   ]
  },
  {
   "title": "Custos Operacionais Totais em Reais - Filial Loja Borges S.A.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT \"CustoOperacional\".\"tipoCusto\" AS \"Tipo\", SUM(\"CustoOperacional\".\"valorMensal\") AS \"Valor Total\" FROM \"CustoOperacional\" INNER JOIN \"Loja\" ON \"CustoOperacional\".\"lojaId\" = \"Loja\".\"lojaId\" WHERE \"Loja\".\"lojaId\" = 1 GROUP BY \"CustoOperacional\".\"tipoCusto\""
    }
   ]
  },
  {
   "title": "Custos Operacionais ao Longo do Tempo em Reais - Filial Loja Ramos Lda.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(\"valorMensal\") AS \"Custo Mensal\", $__timeGroupAlias(\"data\",30d) FROM \"CustoOperacional\" WHERE \"lojaId\" = 2 GROUP BY \"data\" ORDER BY \"data\" ASC"
    }
   ]
  },
  {
   "title": "Custos Operacionais Totais em Reais - Filial Loja Ramos Lda.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT \"CustoOperacional\".\"tipoCusto\" AS \"Tipo\", SUM(\"CustoOperacional\".\"valorMensal\") AS \"Valor Total\" FROM \"CustoOperacional\" INNER JOIN \"Loja\" ON \"CustoOperacional\".\"lojaId\" = \"Loja\".\"lojaId\" WHERE \"Loja\".\"lojaId\" = 2 GROUP BY \"CustoOperacional\".\"tipoCusto\""
    }
   ]
  },
  {
   "title": "Custos Operacionais ao Longo do Tempo em Reais - Filial Loja Araújo S/A",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(\"valorMensal\") AS \"Custo Mensal\", $__timeGroupAlias(\"data\",30d) FROM \"CustoOperacional\" WHERE \"lojaId\" = 3 GROUP BY \"data\" ORDER BY \"data\" ASC"
    }
   ]
  },
  {
   "title": "Custos Operacionais Totais em Reais - Filial Loja Araújo S/A",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT \"CustoOperacional\".\"tipoCusto\" AS \"Tipo\", SUM(\"CustoOperacional\".\"valorMensal\") AS \"Valor Total\" FROM \"CustoOperacional\" INNER JOIN \"Loja\" ON \"CustoOperacional\".\"lojaId\" = \"Loja\".\"lojaId\" WHERE \"Loja\".\"lojaId\" = 3 GROUP BY \"CustoOperacional\".\"tipoCusto\""
    }
   ]
  },
  {
   "title": "Custos Operacionais ao Longo do Tempo em Reais - Filial Loja Maia Loureiro S.A.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(\"valorMensal\") AS \"Custo Mensal\", $__timeGroupAlias(\"data\",30d) FROM \"CustoOperacional\" WHERE \"lojaId\" = 4 GROUP BY \"data\" ORDER BY \"data\" ASC"
    }
   ]
  },
  {
   "title": "Custos Operacionais Totais em Reais - Filial Loja Maia Loureiro S.A.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT \"CustoOperacional\".\"tipoCusto\" AS \"Tipo\", SUM(\"CustoOperacional\".\"valorMensal\") AS \"Valor Total\" FROM \"CustoOperacional\" INNER JOIN \"Loja\" ON \"CustoOperacional\".\"lojaId\" = \"Loja\".\"lojaId\" WHERE \"Loja\".\"lojaId\" = 4 GROUP BY \"CustoOperacional\".\"tipoCusto\""
    }
   ]
  },
  {
   "title": "Custos Operacionais ao Longo do Tempo em Reais - Filial Loja Araújo Pinto Lda.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(\"valorMensal\") AS \"Custo Mensal\", $__timeGroupAlias(\"data\",30d) FROM \"CustoOperacional\" WHERE \"lojaId\" = 5 GROUP BY \"data\" ORDER BY \"data\" ASC"
    }
   ]
  },
  {
   "title": "Custos Operacionais Totais em Reais - Filial Loja Araújo Pinto Lda.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT \"CustoOperacional\".\"tipoCusto\" AS \"Tipo\", SUM(\"CustoOperacional\".\"valorMensal\") AS \"Valor Total\" FROM \"CustoOperacional\" INNER JOIN \"Loja\" ON \"CustoOperacional\".\"lojaId\" = \"Loja\".\"lojaId\" WHERE \"Loja\".\"lojaId\" = 5 GROUP BY \"CustoOperacional\".\"tipoCusto\""
    }
   ]
  }
 ]
}