{
 "title": "Estoque",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Quantidade de Produtos em Estoque por Categoria",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \"Produto\".\"categoria\" AS \"Categoria\", SUM(\"Stock\".\"quantidadeStock\") AS \"Quantidade em Estoque\" FROM \"Produto\" INNER JOIN \"Stock\" ON \"Produto\".\"prodId\" = \"Stock\".\"prodId\" GROUP BY \"Produto\".\"categoria\""
    }
   ]
  },
  {
   "title": "Produtos Abaixo do Nível Mínimo Esperado em Estoque",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \"Produto\".\"prodId\" AS \"ID do Produto\", \"Produto\".\"nome\" AS \"Nome do Produto\", \"Stock\".\"quantidadeStock\" AS \"Quantidade em Estoque\", \"Stock\".\"nivelMin\" AS \"Quantidade Mínima Esperada\", \"Stock\".\"tempoMedioEntrega\" AS \"Tempo Médio de Entrega (dias)\" FROM \"Stock\" INNER JOIN \"Produto\" ON \"Stock\".\"prodId\" = \"Produto\".\"prodId\" WHERE \"Stock\".\"quantidadeStock\" < \"Stock\".\"nivelMin\" ORDER BY \"Stock\".\"tempoMedioEntrega\" DESC"
    }
   ]
  },
  {
   "title": "Produtos Acima do Nível Máximo Esperado em Estoque",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT \"Produto\".\"prodId\" AS \"ID do Produto\", \"Produto\".\"nome\" AS \"Nome do Produto\", \"Stock\".\"quantidadeStock\" AS \"Quantidade em Estoque\", \"Stock\".\"nivelMax\" AS \"Quantidade Máxima Esperada\", \"Stock\".\"tempoMedioEntrega\" AS \"Tempo Médio de Entrega (dias)\" FROM \"Stock\" INNER JOIN \"Produto\" ON \"Stock\".\"prodId\" = \"Produto\".\"prodId\" WHERE \"Stock\".\"quantidadeStock\" > \"Stock\".\"nivelMax\" ORDER BY \"Stock\".\"quantidadeStock\" DESC"
    }
   ]
  }
 ]
}